import type { CaseStudy } from "@/lib/types";

export const documentIntelligence: CaseStudy = {
  slug: "document-intelligence",

  service: "Document search & Q&A",
  serviceSummary:
    "Ask a plain question, get an answer from your own documents with the source named. No more hunting through folders.",

  industry: "Construction & contracting",
  title: "Project documents that answer questions instead of being searched",
  premise:
    "Specs, RFIs, and site reports pile up across a project folder. This system indexes them once, then answers plain questions against them — and names the document every answer came from.",

  glance: {
    trigger: "A question asked in chat, against a pre-indexed document set",
    runMode: "Answers only from indexed documents, never from general knowledge",
    stack: ["n8n", "Gemini embeddings", "Supabase pgvector", "Google Drive"],
    integrations: ["Google Drive", "Supabase"],
  },

  problem: [
    "The answer to a site question usually exists, buried in a document nobody remembers the name of.",
    "Keyword search fails when the document phrases it differently from the person asking.",
    "Checking takes a person who already knows the project, which makes them the bottleneck for everyone else.",
    "An answer given from memory carries no traceable source, which is a problem when the question is contractual.",
  ],

  solution: [
    "An indexing run reads every document in the project folder, so adding files is a folder operation rather than a system task.",
    "Each document is split into overlapping chunks and tagged with its source filename before anything is embedded.",
    "Chunks are embedded with Gemini and stored in Supabase pgvector, so retrieval matches on meaning rather than exact wording.",
    "A question is embedded the same way and matched against the store, pulling back the closest passages.",
    "Source filenames are attached to the retrieved passages in code before the model sees them, so citations come from the retrieval step rather than from the model's account of it.",
    "The answering prompt is restricted to the retrieved context, with an explicit instruction to say so when the answer isn't there.",
  ],

  result: [
    "Every answer names the document it came from, and that filename is carried through by the pipeline rather than generated by the model.",
    "A question the documents don't cover returns a plain statement to that effect instead of a plausible invention.",
    "Retrieval matches meaning, so a question phrased in site language still finds a passage written in spec language.",
    "Indexing and answering are separate pipelines, so re-indexing after new documents arrive doesn't disturb anything on the query side.",
  ],

  diagrams: [
    {
      title: "Indexing pipeline",
      caption:
        "Runs once per document set. Source filenames are attached before embedding, not after.",
      nodes: [
        {
          id: "run",
          label: "Indexing run starts",
          category: "trigger",
          service: "Manual",
          position: { x: 0, y: 0 },
        },
        {
          id: "pull",
          label: "Pull project documents",
          category: "action",
          service: "Google Drive",
          position: { x: 260, y: 0 },
        },
        {
          id: "chunk",
          label: "Split & tag source",
          category: "logic",
          position: { x: 520, y: 0 },
        },
        {
          id: "embed",
          label: "Generate embeddings",
          category: "ai",
          service: "Gemini",
          position: { x: 780, y: 0 },
        },
        {
          id: "store",
          label: "Store in vector database",
          category: "action",
          service: "Supabase",
          position: { x: 1040, y: 0 },
        },
      ],
      edges: [
        { id: "i1", source: "run", target: "pull" },
        { id: "i2", source: "pull", target: "chunk" },
        { id: "i3", source: "chunk", target: "embed" },
        { id: "i4", source: "embed", target: "store" },
      ],
    },
    {
      title: "Query pipeline",
      caption:
        "Sources are attached in code between retrieval and answering, so the citation can't be invented.",
      nodes: [
        {
          id: "ask",
          label: "Question asked",
          category: "trigger",
          service: "Chat",
          position: { x: 0, y: 0 },
        },
        {
          id: "qembed",
          label: "Embed the question",
          category: "ai",
          service: "Gemini",
          position: { x: 260, y: 0 },
        },
        {
          id: "retrieve",
          label: "Find matching passages",
          category: "action",
          service: "Supabase",
          position: { x: 520, y: 0 },
        },
        {
          id: "attach",
          label: "Attach source filenames",
          category: "logic",
          position: { x: 780, y: 0 },
        },
        {
          id: "answer",
          label: "Answer from context only",
          category: "ai",
          service: "Gemini",
          position: { x: 1040, y: 0 },
        },
      ],
      edges: [
        { id: "q1", source: "ask", target: "qembed" },
        { id: "q2", source: "qembed", target: "retrieve" },
        { id: "q3", source: "retrieve", target: "attach" },
        { id: "q4", source: "attach", target: "answer" },
      ],
    },
  ],
};